version: "3.9"

services:
  # PHP 8.1 minimum (CLI version)
  # ----------------------------------------------- #
  php:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: smartping_php
    volumes:
      - ./:/app
    working_dir: /app

  # Composer executable
  # ----------------------------------------------- #
  composer:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: smartping_php_composer
    depends_on:
      - php
    entrypoint: composer
    volumes:
      - ./:/app
    working_dir: /app

  # PestPHP for testing
  # ----------------------------------------------- #
  pest:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: smartping_php_pest
    depends_on:
      - php
    entrypoint: /app/vendor/bin/pest
    volumes:
      - ./:/app
    working_dir: /app

  # Psalm static analysis
  # ----------------------------------------------- #
  psalm:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: smartping_php_psalm
    depends_on:
      - php
    entrypoint: /app/vendor/bin/psalm
    volumes:
      - ./:/app
    working_dir: /app
